### ISSUE TITLE
Heads up: Transferring this Repo to PghFrankenstein Organization 

### ISSUE THREAD

**Issue by ebeshero** [PghFrankenstein/Pittsburgh_Frankenstein#42]
@scottbot @mjlavin80 @raffazizzi @djbpitt @ljo @Rikkm Everyone collaborating the Pittsburgh Frankenstein repo: We've all seen how long it takes to clone this repo the first time because we've been storing a directory full of high-res page images from multiple editions. A week or two back, after watching @djbpitt suffer through trying to clone our repo, I decided to move the directory of facsimile images into its own repo, and set up [a proper PghFrankenstein Organization](https://github.com/PghFrankenstein) for us here in GitHub, where we can have multiple repositories in place for various things we're working on. I'd like to transfer this repo to the organization without losing the Issues and maintaining everyone's history with the repo. On [consultation with GitHub](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization), I've learned this will only work if all of you come and join the organization. Would you all simply [join the organization on my invitation]((https://github.com/PghFrankenstein)) if you haven't done so already? (I think following the link to the organization will do the trick.)

I'm going to issue invitations to each of you (and yes, I may have done so already). I'm also going to launch [a backup of the full repository (including issues, pull requests, etc)](https://help.github.com/articles/backing-up-a-repository/) *before* I attempt to move the repo. As soon as you've all responded and I've done the backup, I'll migrate this repo into the organization and we'll be...a little better organized!

**Comment by ebeshero** [comment]
I've transferred the repo to the new organization. Didn't do the backup, but everything appears to be safely transferred. We should initiate a system of backups.

**Comment by ebeshero** [comment]
Note: You'll want to reset the remote origin for your local repos thus:
```
git remote set-url origin https://github.com/PghFrankenstein/Pittsburgh_Frankenstein.git
```

**Comment by raffazizzi** [comment]
Done, thanks!
