### ISSUE TITLE
Pointers: "otherwise" output?  

### ISSUE THREAD

**Issue by ebeshero** [PghFrankenstein/Pittsburgh_Frankenstein#43]
Hi @raffazizzi -- Skimming the output, it's certainly a lot easier to read! I notice you're flagging an "otherwise" condition and we've got some "otherwises" turning up in the output, like here: What's the otherwise condition? (Is it a margin-zone?)
https://github.com/PghFrankenstein/Pittsburgh_Frankenstein/blob/aa3c50d601a32987da2d929f01d4684d2c7e41f9/collateXPrep/standoff/sga_collation_C15.xml#L252

**Comment by ebeshero** [comment]
Also, I'll pull this in as soon as I've finished processing a last round of collation: this is just picking up the collation units in which we have extra, sometimes multiple fragments in the Bodleian notebooks--for example, ~3 different versions of the very ending.

**Comment by raffazizzi** [comment]
@ebeshero That was just for debugging and it's not supposed to be there, i mistakenly left it in! Will remove it from the XSLT and output
