### ISSUE TITLE
Hypothesis API 

### ISSUE THREAD

**Issue by ebeshero** [PghFrankenstein/Pittsburgh_Frankenstein#47]
@raffazizzi @Rikkm This is what we're currently using (thanks to Jon Udell at hypothes.is) to extract the annotations: https://jonudell.info/h/facet/
I think we're not getting all the info we could be getting from this, though. Since hypothes.is is an open annotation standard, @raffazizzi notes it should have RDF and JSON-LD output. That jives with what Jon Udell sent me this week about alternate approaches to "attaching" annotations that aren't URL dependent, but *instead* work with a *URN made from metadata common to multiple editions*. This looks pretty much like what we need, doesn't it, for attaching the annotations to multiple reading views?  See https://blog.jonudell.net/2017/11/28/syndicating-annotations/

**Comment by ebeshero** [comment]
@raffazizzi @Rikkm For this to work, I *think* we need to be constructing URN attributes that point out something in common across the editions at each moment of variance. (I know that sounds bizarre, but we can't create a meaningful `<app>` unless there's some evidence of a running stream of something-shared-in-common-at-this-moment. Each edition has different chapter numbers, so this can't be so simple as identifying a single chapter, but....maybe we need to express some simple alignment information, like (just making this up): At X moment of variance, we are in:
SGA: chapter 7
1818 Thomas and 1823: chapter 4
1831: chapter 5

And maybe that's expressed thus as the distinctive part of the URN: 
wsga-7_w18-4_wTh-4_w23-4_w31-5

Okay that gets us to chapters, but distinct locations in those chapters? Hmm. Here I wonder if we might need the benefit of string location numbers, @raffazizzi ? 

Here, I also believe we want the Pgh edition annotations to be anchored on Pgh Frankenstein "bridge editions", so that chapter boundaries would make sense here as they wouldn't in pointers to the S-GA files.

**Comment by ebeshero** [comment]
...however(!) I imagine in isolating string location information, we'd also readily be drawing information about where this passage is located in S-GA as well. I wonder if that annotation layer might transfer over to S-GA, too. Curious!

**Comment by judell** [comment]
> I think we're not getting all the info we could be getting from this, though

That's true! I've been adding export formats to that tool on demand, so now that you've asked for JSON, I will add it :-)

Meanwhile, to see what it looks like, try clicking the Share button on an annotation card. The URL you get will look like this:

https://hyp.is/EvSV5FRoEeikyxNbnRVVVQ/www.example.com

https://hypothes.is/api/annotations/EvSV5FRoEeikyxNbnRVVVQ: The "plain vanilla" format, which predates the W3C standard, and which we still use internally.

https://hypothes.is/api/annotations/EvSV5FRoEeikyxNbnRVVVQ.jsonld: The W3C-ified flavor.

**Comment by mdlincoln** [comment]
Now being handled in https://github.com/PghFrankenstein/fv-postCollation/issues/3
