### ISSUE TITLE
Standoff Pointers to All Editions 

### ISSUE THREAD

**Issue by ebeshero** [PghFrankenstein/Pittsburgh_Frankenstein#52]
@raffazizzi I've been tinkering with XSLT on my way home from DHSI, but figured I'd better run some questions here right now about what we want for the TEI output for our edition. Here's what I'm thinking: 

* One TEI output is simply an up-converted form (with TEI "trimmings") around the collation XML output we generated. I've been thinking of this as a kind of "spinal column" for our output collation. (See, for a basic idea: https://github.com/PghFrankenstein/Pittsburgh_Frankenstein/blob/Text_Processing/collateXPrep/C10_xmlOutput/teiUp-tester.xml )  This would be the *source* of pointers into separate edition files.

* The separate edition files: Here I'm imagining we generate these in TEI (rather than HTML) first, and that we make for each edition a TEI document holding an element that contains a "hotspot" area that indicates a place where this edition varies from the others. I know how to make this for an HTML output from TEI (it's the sort of thing I'd wrap an HTML `<span>` around). But I'd like to find a similar element in the TEI for holding this information. I can think of two options for this: 
1) Just keep the `<app>` element (though this seems strange) to mark a variant passage. The problem with this is we'll have places where the up-converted single edition (when we un-flatten its paragraph tags for example) will have conflicting hierarchies. Say this edition has a paragraph break where the others do not: its internal tagging will force us to break up the `<app>` element, and we'll need a way to mark this is the beginning segment of a "hotspot", to be followed by an ending segment. 
2)  For the individual edition files, just use a `<seg>` element for short segments inside paragraphs, with some appropriate attribute to indicate variance info as a hook into the other editions.

I'm planning to study the TEI options typically in use for this kind of thing in the Guidelines after I get done with an afternoon meeting today, but if you have some ideas, please post here! I'll add more as I'm working on this. Outputting the individual editions won't be too difficult once I get through parsing the flattened tags, and I hope to have something up by tonight for us to tinker with.

**Comment by ebeshero** [comment]
Here's a basic idea for the first, super-easy "spinal column" TEI output, holding just collation unit 10 for the moment: https://github.com/PghFrankenstein/Pittsburgh_Frankenstein/blob/Text_Processing/collateXPrep/C10_xmlOutput/teiUp-tester.xml

**Comment by raffazizzi** [comment]
Hello!

1. Sounds good, though after we have a (curated) stand-off collation pointing to all the documents, we should be able to generate this TEI by resolving the pointers. (This could be a good test to prove that our approach works)

2. In the past I have used "semantically weak" elements (though my supervisor wasn't too happy with this choice of words) such as `<w>` or `<seg>`. To me `<seg>` is the closest it gets to HTML's `<span>`. I don't think we need to leave any information about other sources in there: the collation provides those. Real life example from Early Modern Songscapes:

**L638_1.xml***
```xml
<lg type="stanza">
        <l><hi rend="italic" xml:id="test">THesus,</hi> O <hi rend="italic">Thesus,</hi> hark! but yet in vain;</l>
          <l rend="indent2">A-las <w xml:id="v1">de–-ser-ted</w> I complain;</l>
        <!-- etc. -->
      </lg>
``` 
**BL_53723.xml**
```xml
<lg type="stanza">
          <l>Theseous! ô theseus! heark! but yet in vaine,</l>
          <l rend="indent2">alas <w xml:id="v1">forsaken</w> I Complaine;</l>
        <!-- etc. -->
      </lg>
```

**Standoff collation**
```xml
<app>
  <rdg wit="#BL_53723">
    <ptr target="BL_53723.xml#v1"/>
  </rdg>
  <rdg wit="#L638_1">
    <ptr target="L638_1.xml#v1"/>
  </rdg>
</app>
```
