### ISSUE TITLE
Adjustments needed to spines

### ISSUE THREAD

**Issue by raffazizzi** [PghFrankenstein/Pittsburgh_Frankenstein#58]
Assessment based on [spine_C10](https://raw.githubusercontent.com/PghFrankenstein/Pittsburgh_Frankenstein/Text_Processing/collateXPrep/standoff_Spine/spine_C10.xml)

* do not use `<ref>`s
* currently there aren't any multiple `<ptr>`s within an `<rdg>`: those are needed when there are multiple `<seg>`s that need to be referred together. Is this still missing from the processing?
* Related to the above, we had specific IDs for <seg>s split over hierarchies and they looked like this: `C10_app2-f1818__Pt1`. This may be obsolete now (given `@part`) and not needed for processing

PS this is [how spine_C10.xml looked in CDMX](https://github.com/PghFrankenstein/Pittsburgh_Frankenstein/blob/452b8ab6589fbcc8f1e865150c6a1e42a72c617b/collateXPrep/standoff_Spine/spine_C10.xml)

**Comment by ebeshero** [comment]
@raffazizzi Here's a spinal readjustment for C-10: https://github.com/PghFrankenstein/Pittsburgh_Frankenstein/blob/Text_Processing/collateXPrep/standoff_Spine/spine_C10-recon.xml 

(Note: I renamed the file in case we need to debug it. The old one is still in place at spine_C10.xml)
A number of `<app>` elements disappeared this round because in the up-conversion process to make `<seg>` hotspots, I eliminated all that came from invariant `<app>`s. So this spine should be more streamlined.

**Comment by ebeshero** [comment]
@raffazizzi All of my C10 edition files are up-converted and ready for pointing. They are in the same directory as before for Mexico City: https://github.com/PghFrankenstein/Pittsburgh_Frankenstein/tree/Text_Processing/collateXPrep/bridge-P5-C10

**Comment by ebeshero** [comment]
@raffazizzi However, at the moment we still only have C10.  We'll figure the rest out for the full novel, but not in time for this talk.

**Comment by ebeshero** [comment]
@raffazizzi Well! I figured out what I was doing wrong, reprocessed everything, set the proper `<seg>` markers and upconverted the entire novel! w00t!!!!  

SO, that changes things a bit. I reconstructed the spine files for all 33 "chunks" here: https://github.com/PghFrankenstein/Pittsburgh_Frankenstein/tree/Text_Processing/collateXPrep/standoff_Spine  

The old spine from July 23 is in a different directory now in case we want to look at it  (orig_standoff_Spine). As I mentioned earlier, the new spine files produced in this later stage will not contain the invariant `<app>` elements that the first spine did. 

The complete novel edition files are now ready (yaaayyyy!) here: https://github.com/PghFrankenstein/Pittsburgh_Frankenstein/tree/Text_Processing/collateXPrep/bridge-P5

Take a look and let's see if this spine will work!  Currently the spine I generated is pointing at my local versions of the S-GA files, so I think you now run your script to build the S-GA pointers...I hope it works!!!

**Comment by raffazizzi** [comment]
@ebeshero Thanks for all this work and hurrah for figuring the `<seg>`s out!

The links in the spine are incorrect, but it should be simple to fix in the processing. 
Example from C21:

`<rdg wit="#f1818"><ptr target="https://raw.githubusercontent.com/PghFrankenstein/Pittsburgh_Frankenstein/Text_Processing/collateXPrep/bridge-P5-C10/#C21_app1-f1818__Pt1"/>`

should be
`<rdg wit="#f1818"><ptr target="https://raw.githubusercontent.com/PghFrankenstein/Pittsburgh_Frankenstein/Text_Processing/collateXPrep/bridge-P5/P5-f1818_C22.xml#C21_app1-f1818__Pt1"/>`

**Comment by ebeshero** [comment]
Thanks for catching that, @raffazizzi !

**Comment by ebeshero** [comment]
Closing here because we're now generating spines in the fv-postProcessing repo, and will check the status of spines again there.
