### ISSUE TITLE
Add Matt Lincoln to PghFrankenstein organization

### ISSUE THREAD

**Issue by mdlincoln** [PghFrankenstein/Pittsburgh_Frankenstein#60]
Greetings from CMU! When you can, @ebeshero, can you add me to the [PghFrankenstein](https://github.com/PghFrankenstein) org? Looking forward to working with everyone on here :)

**Comment by ebeshero** [comment]
Welcome, @mdlincoln ! I think someone may have added you last night, but let me check...

**Comment by ebeshero** [comment]
@mdlincoln I believe you've been invited now! We'll have lots to talk about to orient you to what's here...let's talk soon! :-)

**Comment by mdlincoln** [comment]
Thank you!
